version: 2.1

jobs:
  generate-sign:
    docker:
      - image: cimg/base:2022.11
    steps:
      - run: |
          t=$(date +%s%3N)
          nonce=$(< /proc/sys/kernel/random/uuid)
          sign=$(echo -n "$TOKEN$t$nonce" | openssl dgst -binary -sha256 -hmac "$SECRET" | base64)
          echo "export T=$t" >> $BASH_ENV
          echo "export NONCE=$nonce" >> $BASH_ENV
          echo "export SIGN=$sign" >> $BASH_ENV

  bot-action:
    docker:
      - image: cimg/base:2022.11
    steps:
      - checkout
      - run: |
          source ./bot.conf
          echo $command
          echo curl -X POST \
               -H "Content-Type: application/json; charset=utf8" \
               -H "Authorization: $TOKEN" \
               -H "t: $T" \
               -H "sign: $SIGN" \
               -H "nonce: $NONCE" \
               -d '{"command": "'$command'", "paramter": "default", "commandType": "default"}' \
               "https://api.switch-bot.com/v1.1/devices/$BOT_DEVICE_ID/commands"

workflows:
  version: 2
  bot-action:
    jobs:
      - generate-sign
      - bot-action:
          requires:
            - generate-sign
